name: Build Dotnet SDK

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4.1.1
  
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1

    - name: Move Files
      run: |
        mdir out
        mv editors/*.* out/

    - name: Build Markdown
      run: |
        cd editors/markdown
        npm i
        npm run build-editor
        mv dist/index.html dist/old-markdown.html
        mv dist/* ../../out/

    - name: Build Rich Text
      run: |
        cd editors/richtext
        npm i
        npm run build-editor
        mv dist/index.html dist/old-richtext.html
        mv dist/* ../../out/
     
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        branch: gh-pages
        folder: out
        target-folder: editors
        clean: true
